version: "3"
services:

  bazel:
    build:
      context: dockerfile
      dockerfile: bazel.Dockerfile
    working_dir: /root/src
    volumes:
    - $PWD:/root/src:rw
    - $XDG_CACHE_HOME/bazel:$XDG_CACHE_HOME/bazel:rw
    environment:
    - XDG_CACHE_HOME=$XDG_CACHE_HOME
    entrypoint:
    - /bin/bash
    - -c
    - |
      [ $XDG_CACHE_HOME ] && echo "startup --output_user_root=$XDG_CACHE_HOME/bazel" >> .bazelrc
      bazel test --test_output=errors ...
