version: "3"
services:

  mitmproxy:
    image: mitmproxy/mitmproxy
    ports:
    - 8080:8080
    - 8081:8081
    command: mitmweb --web-iface 0.0.0.0
    volumes:
    - ~/.mitmproxy:/home/mitmproxy/.mitmproxy
