version: "3"
services:

  tinyproxy:
    image: michilu/docker-tinyproxy
    ports:
    - 443:8888
    - 9000:9000
    command: ${TINYPROXY_WEBHOOK_URLPREFIX}
    environment:
      TINYPROXY_DISABLE_VIA_HEADER: ${TINYPROXY_DISABLE_VIA_HEADER}
