version: "3"
services:

  travis-worker-bazel:
    build:
      context: dockerfile/travis-worker-bazel
    volumes:
    - $PWD:/home/travis/src:rw,delegated
    - $XDG_CACHE_HOME/bazel:$XDG_CACHE_HOME/bazel:rw,delegated
    environment:
    - XDG_CACHE_HOME=$XDG_CACHE_HOME
    entrypoint:
    - /bin/bash
    - -c
    - |
      ./setup.sh && ./src/build.sh
